doDownloadZips: False
doExtractMDB: False
doCreateDatasets: False
dataFolder: C:/ENES/
dataFolderMDB: C:/ENES/MDB/
dataFolderZIP: C:/ENES/ZIP/
dataFolderParquet: C:/ENES/Parquet/
verbose: True
ignore_known_warnings: True
