doDownloadZips: False
doExtractMDB: False
doCreateDatasets: True
dataFolder: C:/ENES/
dataFolderMDB: C:/ENES/MDB/
dataFolderZIP: C:/ENES/ZIP/
dataFolderParquet: C:/ENES/Parquet/
verbose: False
ignore_known_warnings: True
